### ISSUE TITLE
.Sites.First deprecated

### ISSUE THREAD

**Issue by pleasantone** [hbstack/preferred-language#169]
❯ hugo
Start building sites …
hugo v0.133.0+extended darwin/arm64 BuildDate=2024-08-17T19:57:41Z VendorInfo=brew

WARN  deprecated: .Sites.First was deprecated in Hugo v0.127.0 and will be removed in a future release. Use .Sites.Default instead.

FYI this also occurs in a few hugomods modules too.

**Comment by razonyang** [comment]
Thanks for pointing this out, will draft patch releases for related module.

**Comment by razonyang** [comment]
Done, upgrade modules should fix this, if not, wait a while and then try again, since those modules were just released, there maybe caches stuff, so you may not get the latest version of modules.

Updated modules:

1. hbstack/preferred-language
2. hbstack/hb
3. hugomods/search
4. hugomods/code-block-panel
